### ISSUE TITLE
Add a Server landing Page

### ISSUE THREAD

**Issue by stealthanthrax** [NJACKWinterOfCode/youtube_cli_flask#15]
**Is your feature request related to a problem? Please describe.**
Currently, the server opens up on localhost:7070 and no page is returned on localhost:7070/

**Describe the solution you'd like**
To return a basic index.html file for the '/' endpoint.

**Comment by vipulbhj** [comment]
I have done the templating please check again in my last PR

**Comment by vipulbhj** [comment]
@stealthanthrax This has already been fixed by me in my last PR, please check and close this issue.

**Comment by stealthanthrax** [comment]
@vipulbhj , okay just saw it right now. Please try to solve one issue per PR in the future, as otherwise it sometimes creates a mess.
