### ISSUE TITLE
Add an endpoint to get an input of the playlist and shuffle it using Fisher Yates Algo

### ISSUE THREAD

**Issue by stealthanthrax** [NJACKWinterOfCode/youtube_cli_flask#29]
**Is your feature request related to a problem? Please describe.**
Get a list of songs and shuffle it in a linear complexity or smaller.

**Describe the solution you'd like**
Use Fisher Yates Algo

**Describe alternatives you've considered**
Using the random.shuffle isn't very effective as it uses n^2 complexity(probably)

**Additional context**
I'd be working on this

**Comment by abhiroopdutta** [comment]
How will the input playlist be generated?

**Comment by stealthanthrax** [comment]
I have a vague mechanism in my mind right now, I'll have to document it first myself and then I'll add the methods in the repo.

**Comment by abhiroopdutta** [comment]
Ok I’ll try to implement the Fisher Yates algo at least  😁

**Comment by sansyrox** [comment]
Moved to the main repo https://github.com/stealthanthrax/kasper_music_player/issues/9
