### ISSUE TITLE
Create a logo for this App

### ISSUE THREAD

**Issue by stealthanthrax** [NJACKWinterOfCode/youtube_cli_flask#30]
**Is your feature request related to a problem? Please describe.**
Create a logo for this App according to the decided name

**Describe the solution you'd like**
Currently, the decided name is "Kasper" as it is similar to Napster and follows the same motive of providing free music

**Additional context**

**Comment by saurabhshadow** [comment]
Can I over this?

**Comment by stealthanthrax** [comment]
Sure @saurabhshadow .
Would you like to discuss some ideas ??

**Comment by stealthanthrax** [comment]
So , the decided name is Kasper. And Casper was the friendly ghost . Can you make a ghost maybe like snapchat wearing a headphone and some music around yes.

**Comment by saurabhshadow** [comment]
okay. I'll let you know about the updates by tomorrow.

**Comment by saurabhshadow** [comment]
> So, the decided name is Kasper. And Casper was the friendly ghost. Can you make a ghost maybe like snapchat wearing a headphone and some music around?

I can make this.

**Comment by stealthanthrax** [comment]
Okay @saurabhshadow . Good Luck 👍

**Comment by saurabhshadow** [comment]
![kasper](https://user-images.githubusercontent.com/44670849/50377198-fafaf300-063e-11e9-9c47-c703f4c5147a.jpg)
I have made this and I really love this!
Hope you'll love it too!

**Comment by saurabhshadow** [comment]
Can u tell me the color code of blue color that u have used?

**Comment by stealthanthrax** [comment]
@saurabhshadow , you can use this photo as a reference for the different shades of blues that I want to include in my app.

![49032260-24f0ff00-f1d2-11e8-824e-921c5b65c68b](https://user-images.githubusercontent.com/29942790/50420969-8acbb780-0860-11e9-9880-cc44aa68426a.jpg)

**Comment by saurabhshadow** [comment]
![kasper3](https://user-images.githubusercontent.com/44670849/50471222-ab6b4d00-09d9-11e9-8dfd-4331bdc1c95b.jpg)
![kasper31](https://user-images.githubusercontent.com/44670849/50471237-b6be7880-09d9-11e9-9a5e-544b14016fe3.jpg)

I have made these!
Please have a look!

**Comment by saurabhshadow** [comment]
![kasper32](https://user-images.githubusercontent.com/44670849/50471474-ca1e1380-09da-11e9-8c93-f8333d5db3f5.jpg)

with name

**Comment by stealthanthrax** [comment]
Woah!!! @saurabhshadow , these are rad 🔥 🔥 

Can you make one where the ghost is with blue outline and black text on the right?

**Comment by stealthanthrax** [comment]
And maybe one avatar with eyes like these? 
![casper_logo](https://user-images.githubusercontent.com/29942790/50475356-73b8d100-09ea-11e9-941e-b436ed4fc838.png)

**Comment by saurabhshadow** [comment]
![kasper36](https://user-images.githubusercontent.com/44670849/50486142-80efb300-0a1e-11e9-8949-6be413748b5d.jpg)
![kasper37](https://user-images.githubusercontent.com/44670849/50486143-81884980-0a1e-11e9-83af-7616b3011607.jpg)
![kasper38](https://user-images.githubusercontent.com/44670849/50486144-81884980-0a1e-11e9-80f6-9c2912595440.jpg)



![Uploading kasper43.jpg…]()
![Uploading kasper455.jpg…]()

**Comment by saurabhshadow** [comment]
![kasper455](https://user-images.githubusercontent.com/44670849/50488691-b352dd80-0a29-11e9-93ef-1cf3864e1c46.jpg)

**Comment by saurabhshadow** [comment]
![kasper41](https://user-images.githubusercontent.com/44670849/50488708-ccf42500-0a29-11e9-8969-8e100fb42962.jpg)
![kasper43](https://user-images.githubusercontent.com/44670849/50488709-cd8cbb80-0a29-11e9-82b3-d3d0bd93f25a.jpg)

**Comment by saurabhshadow** [comment]
> And maybe one avatar with eyes like these?
> ![casper_logo](https://user-images.githubusercontent.com/29942790/50475356-73b8d100-09ea-11e9-941e-b436ed4fc838.png)

I have made these...please have a look!

**Comment by saurabhshadow** [comment]
I have made these ..
please have a look!

**Comment by stealthanthrax** [comment]
@saurabhshadow , make a PR with this logo https://user-images.githubusercontent.com/44670849/50471237-b6be7880-09d9-11e9-9a5e-544b14016fe3.jpg

and this font https://user-images.githubusercontent.com/44670849/50488709-cd8cbb80-0a29-11e9-82b3-d3d0bd93f25a.jpg

add design files too.
Good work 🚀

**Comment by saurabhshadow** [comment]
> @saurabhshadow , make a PR with this logo https://user-images.githubusercontent.com/44670849/50471237-b6be7880-09d9-11e9-9a5e-544b14016fe3.jpg
> 
> and this font https://user-images.githubusercontent.com/44670849/50488709-cd8cbb80-0a29-11e9-82b3-d3d0bd93f25a.jpg
> 
> add design files too.
> Good work 🚀

Created a pull request #44

**Comment by sansyrox** [comment]
Completed
