### ISSUE TITLE
Write Tests for the backend

### ISSUE THREAD

**Issue by stealthanthrax** [NJACKWinterOfCode/youtube_cli_flask#32]
**Is your feature request related to a problem? Please describe.**
Currently, no tests are present for the server.py file.

**Describe the solution you'd like**
Create a test folder and start writing tests for the server

**Additional context**
PyTest library should be used for these

**Comment by sansyrox** [comment]
Moved to the main repo https://github.com/stealthanthrax/kasper_music_player/issues
