### ISSUE TITLE
Send videoId to front-end

### ISSUE THREAD

**Issue by abhiroopdutta** [NJACKWinterOfCode/youtube_cli_flask#39]
**Describe the bug**
The frontend does not have the currently playing song's video_id, so cannot make recommendations based on that song.

**Expected behavior**
Every time a new song is played, we send the video_id of that song to the frontend, so that using the current song's video_id, a call to the @recommended endpoint can be made and new songs can be recommended based on that song.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Issue #36 is dependent on this issue.

**Comment by stealthanthrax** [comment]
@abhiroopdutta ,the right workflow would be to first connect the search bar and then request video ids on the search button click.

**Comment by abhiroopdutta** [comment]
Yeah, right, that's what I was saying.
