### ISSUE TITLE
Add API Endpoint to recommend youtube playable links in JSON format

### ISSUE THREAD

**Issue by stealthanthrax** [NJACKWinterOfCode/youtube_cli_flask#5]
This should be done using youtube-dl and pafy

**Comment by abhiroopdutta** [comment]
The user should be able to see the titles of the recommended songs right ? And based on their selection, the song should start playing. So we can generate the titles and videoIds of the songs in JSON and give it to the front end, then based on the videoId we receive we can use the @/song_wo_ytdata endpoint to start playing the song?

**Comment by stealthanthrax** [comment]
@abhiroopdutta, that's a great suggestion, go ahead and implement in the app ✨
