### ISSUE TITLE
Remove excess code from the front-end part

### ISSUE THREAD

**Issue by stealthanthrax** [NJACKWinterOfCode/youtube_cli_flask#7]

**Comment by vipulbhj** [comment]
What does this mean ??

**Comment by stealthanthrax** [comment]
As of now, the front-end part is just a basic 'create-react-app' template. There are many parts like the frontend README,logo.svg etc. That are not required.

**Comment by stealthanthrax** [comment]
As of now, the front-end part is just a basic 'create-react-app' template. And some files like the front-end README is not required.

**Comment by vipulbhj** [comment]
Cool, I will take this issue. Thanks

**Comment by vipulbhj** [comment]
Should I remove all the unimportant parts and simple it to say frontend or the app name or something ??

**Comment by vipulbhj** [comment]
@stealthanthrax Please Close this as well and can you please also take a look at my marks. I don't think the score is correct
